language: node_js
node_js:
  #  - '10'
  - '12'
os: linux
install:
  - yarn --frozen-lockfile
  - yarn workspace asuna-admin build
  - yarn global add codecov
after_success:
  - codecov
#cache:
#  yarn: true
